/** @type {import('tailwindcss').Config} */
const colors = require("tailwindcss/colors");

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    colors: {
      white: colors.white,
      gray: colors.gray,
      indigo: colors.indigo,
      red: colors.red,
      green: colors.green,
      yellow: colors.yellow,
      pink: colors.pink,
      blue: colors.blue,
      darkblue: colors.darkblue,
      "primary-navbar": "#1B50DB",
      "primary-10": "#cedbe9",
      "primary-50": "#86a5c8",
      primary: "#1363DF",
      "primary-text": "#0090FF",
      "primary-dark": "#005699",
      "primary-hover": "#0287EF",
      "primary-pressed": "#047EDE",
      "primary-ghost-hover": "#E8EDF2",
      "primary-ghost-pressed": "#FFFFFF",

      "error-10": "#FFD8DC",
      "error-50": "#FF9FA8",
      error: "#FF3E51",
      "error-text": "#FF3E51",
      "error-dark": "#992531",
      "error-hover": "#E83E52",
      "error-pressed": "#D23D53",
      "error-ghost-hover": "#F0EBED",
      "error-ghost-pressed": "#EBE0E3",

      "success-10": "#CCF5E4",
      "success-50": "#80E5BB",
      success: "#01CC78",
      "success-text": "#01CC78",
      "success-dark": "#007B48",
      "success-hover": "#01BD76",
      "success-pressed": "#09AE72",
      "success-ghost-hover": "#E9EFEE",
      "success-ghost-pressed": "#DCE9E5",

      "warning-10": "#FEEED2",
      "warning-50": "#FBD48D",
      warning: "#F8AA1C",
      "warning-text": "#F8AA1C",
      "warning-dark": "#97670F",
      "warning-hover": "#E29F24",
      "warning-pressed": "#CC9328",
      "warning-ghost-hover": "#EFEEEC",
      "warning-ghost-pressed": "#ECE7E0",

      contrast: "#192434",
      "contrast-90": "#263445",
      "contrast-80": "#414D5E",
      "contrast-70": "#616D7C",
      "contrast-60": "#747F8E",
      "contrast-50": "#8D97A4",
      "contrast-40": "#A9B1BC",
      "contrast-30": "#C4CAD3",
      "contrast-20": "#D2D7DE",
      "contrast-10": "#E8EBEF",
      "contrast-5": "#F4F5F7",
      "contrast-05": "#193b670d",
    },
    fontSize: {
      "2xs": ".65rem",
      xs: ".7rem",
      sm: ".8rem",
      base: ".875rem",
      lg: "1rem",
      xl: "1.125rem",
      "2xl": "1.25rem",
      "3xl": "1.5rem",
      "4xl": "1.875rem",
      "5xl": "2.25rem",
      "6xl": "3rem",
      "7xl": "4rem",
      "8xl": "5rem",
    },
    screens: {
      xs: "420px",
      sm: "640px",
      md: "821px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    zIndex: {
      "1-": -1,
      0: 0,
      10: 10,
      20: 20,
      30: 30,
      40: 40,
      50: 50,
      75: 75,
      100: 100,
      200: 200,
      300: 300,
      400: 400,
      full: 9999,
      auto: "auto",
    },
    extend: {
      height: {
        'xl': '30rem',
      }
    },
  },
  variants: {
    extend: {
      visibility: ["group-hover"],
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    // require('@tailwindcss/aspect-ratio'),
    require("tailwindcss"),
    require("autoprefixer"),
    require("tailwind-scrollbar"),
    require("@tailwindcss/line-clamp"),
  ],
};
