export const TYPES = {
  SecretsManager: Symbol("SecretsManager"),
  SecretService: Symbol("SecretService"),
  Knex: Symbol("Knex"),
  DbSecretService: Symbol("DbSecretService"),
  JwtAuthService: Symbol("JwtAuthService"),
  RequestUtils: Symbol("RequestUtils"),
  ResponseUtils: Symbol("ResponseUtils"),
  DoctorRepository: Symbol("DoctorRepository"),
  PatientRepository: Symbol("PatientRepository"),
  AppointmentRepository: Symbol("AppointmentRepository"),
  AppointmentService: Symbol("AppointmentService"),
  UserRepositoryFactory: Symbol("UserRepositoryFactory"),
  DoctorMembershipRepository: Symbol("DoctorMembershipRepository"),
  ServiceRepository: Symbol("ServiceRepository"),
};
